### ISSUE TITLE
delete_table_data command error

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#105]
```(venv) C:\Users\Simon\demography_database>python manage.py delete_table_data
Are you sure you want to delete all data? (y/n): y
Traceback (most recent call last):
  File "manage.py", line 802, in <module>
    manager.run()
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\flask_script\__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\flask_script\__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\flask_script\commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "manage.py", line 157, in delete_table_data
    Taxonomy.query.delete()
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2736, in delete
    delete_op.exec_()
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 897, in exec_
    self._do_exec()
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1023, in _do_exec
    params=self.query._params)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1021, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1070, in _execute_context
    context)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1063, in _execute_context
    context)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\sqlalchemy\engine\default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\MySQLdb\cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\Simon\demography_database\venv\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.IntegrityError: (IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`demog_compadre`.`versions`, CONSTRAINT `versions_ibfk_15` FOREIGN KEY (`taxonomy_id`) REFERENCES `taxonomies` (`id`))') 'DELETE FROM taxonomies' ()
```

**Comment by sargentfrancesca** [comment]
This is because of restricted rules on_delete, I'm adding a commit now that looks to fix this, though if your database is already set up, you'll need to change all of the foreign keys' ONDELETE statements to CASCADE manually... annoyingly...

Hoping to use this https://gist.github.com/vkotovv/6281951
