### ISSUE TITLE
Treatment data input error

### ISSUE THREAD

**Issue by simonrolph** [Spandex-at-Exeter/demography_database#30]
Treatment is a string field in the WTForm

in views.py form can be filled with

```
form.treatment.data = matrix.treatment.type_name
```

but submitting with

```
matrix.treatment = form.treatment.data
```

causes

AttributeError: 'unicode' object has no attribute '_sa_instance_state'

```
Traceback (most recent call last):
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/simon/demography_database/app/main/views.py", line 374, in matrix_form
    matrix.treatment = form.treatment.data
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 226, in __set__
    instance_dict(instance), value, None)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 812, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 832, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "/home/simon/demography_database/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 84, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'unicode' object has no attribute '_sa_instance_state'
```

Which mostly makes sense because I'm putting the string from the treatment meta-table into the matrix treatment column, which is just a number referencing a treatment from the meta table. 

But I'm not sure how to go about fixing it!

**Comment by sargentfrancesca** [comment]
Is this one still a problem? the `form.treatment.data` is indeed returning a string, which is the `type_name` of the `Treatment()` model.  So, you will need to query `Treatment()` for an entry with that `type_name`. If it doesn't exist already, then add a new one..

```
treatment = Treatment.query.filter_by(type_name=form.treatment.data).first()
if treatment == None:
    treatment = Treatment(type_name=form.treatment.data)
db.session.add(treatment)
```

**Comment by simonrolph** [comment]
Not sure if it's still an issue, I'll poke it and see if it breaks when I've migrated.

**Comment by sargentfrancesca** [comment]
@simonrolph can this be closed?
